import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/headers/Header";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";
import AuthSavedContextProvider from "@/contexts/contexProviders/AuthSavedContextProvider";
import { ThemeProvider } from "@/components/UI/reusable/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased relative`}
      >
        <div id="toast-root"></div>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthSavedContextProvider>
            <Header />
            <Suspense fallback={<Loading />}>
              {modal}
              {children}
            </Suspense>
          </AuthSavedContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
