import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import CartProvider from "@/contexts/CartContext";
import "./globals.css";
import AuthContextProvider from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <AuthContextProvider>
          <CartProvider>
            <main>
              <Header />
              <div className="pt-20">
                {modal}
                {children}
              </div>
            </main>
          </CartProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
